-- credit_companies 테이블 생성
create table if not exists public.credit_companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null check (category in ('CDS', '외화채', '원화채')),
  active boolean not null default true,
  created_at timestamptz default now()
);

-- RLS 비활성화 (서비스 롤 키로 접근)
alter table public.credit_companies enable row level security;

-- 서비스 롤은 모두 허용
create policy "service role all" on public.credit_companies
  for all using (true) with check (true);

-- 초기 데이터: CDS
insert into public.credit_companies (name, category) values
  ('국민은행', 'CDS'),
  ('신한은행', 'CDS'),
  ('현대카드', 'CDS'),
  ('AIA Group', 'CDS'),
  ('Bank of America', 'CDS'),
  ('Berkshire Hathaway', 'CDS'),
  ('CAFFIL', 'CDS'),
  ('French Republic', 'CDS'),
  ('ING Group', 'CDS'),
  ('KCC', 'CDS'),
  ('LG화학', 'CDS'),
  ('Qatar National Bank', 'CDS'),
  ('SC Bank', 'CDS'),
  ('SK하이닉스', 'CDS'),
  ('State of Qatar', 'CDS'),
  ('Barclays Bank PLC', 'CDS'),
  ('TSMC', 'CDS'),
  ('Goldman Sachs', 'CDS'),
  ('Citi Group', 'CDS'),
  ('Norinchukin Bank', 'CDS'),
  ('India Government', 'CDS'),
  ('India Export Import Bank', 'CDS'),
  ('Deutsche Bank', 'CDS'),
  ('Morgan Stanley', 'CDS');

-- 초기 데이터: 외화채
insert into public.credit_companies (name, category) values
  ('미래에셋증권', '외화채'),
  ('한국가스공사', '외화채'),
  ('한국석유공사', '외화채'),
  ('한국수력원자력', '외화채'),
  ('현대캐피탈아메리카', '외화채'),
  ('LG에너지솔루션', '외화채'),
  ('한국해양진흥공사', '외화채'),
  ('한국주택금융공사', '외화채'),
  ('포스코', '외화채'),
  ('신용보증기금', '외화채'),
  ('하나증권', '외화채');

-- 초기 데이터: 원화채
insert into public.credit_companies (name, category) values
  ('고려아연', '원화채'),
  ('광주광역시도시공사', '원화채'),
  ('광주신세계', '원화채'),
  ('나래에너지서비스', '원화채'),
  ('넥센타이어', '원화채'),
  ('녹십자홀딩스', '원화채'),
  ('다우기술', '원화채'),
  ('대신에프앤아이', '원화채'),
  ('대한항공', '원화채'),
  ('동원시스템즈', '원화채'),
  ('롯데물산', '원화채'),
  ('롯데쇼핑', '원화채'),
  ('메리츠금융지주', '원화채'),
  ('메리츠증권', '원화채'),
  ('미래에셋캐피탈', '원화채'),
  ('부산은행', '원화채'),
  ('비씨카드', '원화채'),
  ('산은캐피탈', '원화채'),
  ('삼성카드', '원화채'),
  ('신세계푸드', '원화채'),
  ('신한카드', '원화채'),
  ('신한캐피탈', '원화채'),
  ('쌍용씨앤이', '원화채'),
  ('엘에스엠트론', '원화채'),
  ('연합자산관리', '원화채'),
  ('우리금융에프앤아이', '원화채'),
  ('우리금융캐피탈', '원화채'),
  ('우리카드', '원화채'),
  ('인천도시공사', '원화채'),
  ('종근당', '원화채'),
  ('증권금융', '원화채'),
  ('지에스엔텍', '원화채'),
  ('케이비캐피탈', '원화채'),
  ('코오롱인더스트리', '원화채'),
  ('키움에프앤아이', '원화채'),
  ('키움증권', '원화채'),
  ('팬오션', '원화채'),
  ('평택도시공사', '원화채'),
  ('폭스바겐파이낸셜서비스코리아', '원화채'),
  ('하나 F&I', '원화채'),
  ('하나카드', '원화채'),
  ('하나캐피탈', '원화채'),
  ('하림지주', '원화채'),
  ('하이트진로홀딩스', '원화채'),
  ('한국광해광업공단', '원화채'),
  ('한국남동발전', '원화채'),
  ('한국남부발전', '원화채'),
  ('한국동서발전', '원화채'),
  ('한국서부발전', '원화채'),
  ('한국전력공사', '원화채'),
  ('한국투자캐피탈', '원화채'),
  ('한국항공우주산업', '원화채'),
  ('현대건설', '원화채'),
  ('현대엔지니어링', '원화채'),
  ('현대엘리베이터', '원화채'),
  ('현대캐피탈', '원화채'),
  ('현대커머셜', '원화채'),
  ('호텔롯데', '원화채'),
  ('BNK캐피탈', '원화채'),
  ('GS건설', '원화채'),
  ('GS이엔알', '원화채'),
  ('HD현대오일뱅크', '원화채'),
  ('HDC현대산업개발', '원화채'),
  ('HL만도', '원화채'),
  ('HS효성첨단소재', '원화채'),
  ('IBK캐피탈', '원화채'),
  ('IM금융지주', '원화채'),
  ('IM캐피탈', '원화채'),
  ('JB금융지주', '원화채'),
  ('JB우리캐피탈', '원화채'),
  ('KB국민카드', '원화채'),
  ('KB금융지주', '원화채'),
  ('NH농협캐피탈', '원화채'),
  ('SE그린에너지', '원화채'),
  ('SK렌터카', '원화채'),
  ('SK에코플랜트', '원화채'),
  ('SK온', '원화채'),
  ('SK이노베이션', '원화채'),
  ('SK인천석유화학', '원화채');
